name: Build

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-chrome:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create archive
        run: |
          mkdir chrome_build
          cp -r src/* chrome_build/
          cp chrome/manifest.json chrome_build/
          cd chrome_build
          zip -r ../chrome.zip .

      - name: Upload to Release
        uses: xresloader/upload-to-github-release@v1
        with:
          file: chrome.zip
          overwrite: true
          update_latest_release: true

  build-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create archive
        run: |
          mkdir firefox_build
          cp -r src/* firefox_build/
          cp firefox/manifest.json firefox_build/
          cd firefox_build
          zip -r ../firefox.zip .

      - name: Upload to Release
        uses: xresloader/upload-to-github-release@v1
        with:
          file: firefox.zip
          overwrite: true
          update_latest_release: true
